version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      markdown-it:
        patterns:
          - "*markdown-it*"
      jest:
        patterns:
          - '*jest*'
      linters:
        patterns:
          - '*eslint*'
      non-major:
        update-types:
          - patch
          - minor
