root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
plugins:
  - tree-shaking
parserOptions:
  sourceType: module
rules:
  "@typescript-eslint/member-delimiter-style": off
  "tree-shaking/no-side-effects-in-initialization": error
