root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
plugins:
  - "@typescript-eslint"
  - tree-shaking
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
rules:
  "@typescript-eslint/member-delimiter-style": off
  "tree-shaking/no-side-effects-in-initialization": error
