name: automatic publish

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup Node
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          cache: npm

      - name: update npm
        run: npm install -g npm@latest

      - name: npm ci
        run: npm ci

      - name: run build
        run: npm run build

      - name: release
        run: npm publish --access public
